runtime: python310  # or your version (python39, etc.)

entrypoint: gunicorn -b :$PORT main:app

instance_class: F2  # Allocates 1 GB memory (F1 = 512MB, F2 = 1GB, F4 = 2GB)

# Optional automatic scaling
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3